Fix failing tests in class_method_test
I was seeing the following 2 failures when running the tests in this
test case:

1. ClassMethodTest#test_should_call_restore_original_method:
   NoMethodError: undefined method `reset_mocha' for #<Class:0x007fc4374b0728>

2. ClassMethodTest#test_should_call_remove_new_method:
   NoMethodError: undefined method `reset_mocha' for #<Class:0x007fc4374aaaa8>

These tests would pass when run using `rake test` because
`Mocha::ObjectMethods` was being included elsewhere which meant that the
real implementation of `reset_mocha` was being invoked.

NOTE. These tests were previously failing in Ruby 1.8.7, 1.9.3, 2.0.0,
2.1, 2.2 and 2.3.