Fix misleading exception message in ParameterMatchers#has_entry
PR: #513

Previously if has_entry was called without any arguments, it raised the
following exception:

    ArgumentError: Too many arguments; use either a single argument
                   (must be a Hash) or two arguments (a key and a value).