MiniTest v1.4.1 is broken on platforms not supporting SIGINFO.
We get the following errors when running on Travis CI [1] :-

    ArgumentError: unsupported signal SIGINFO

Note that I've kept the relevant Gemfile and still run the tests locally
in the build-matrix script, because it works on OSX.

[1] http://travis-ci.org/#!/freerange/mocha/jobs/1858953