Set Minitest.seed for test:performance task
It looks like this may have been required since Minitest v5.16.0 [1].
Without it the following error occurs when a test class is run:

    TypeError: no implicit conversion of nil into Integer

[1]: https://github.com/minitest/minitest/blob/4accdd55c1475f774273145f0f6c8da4ba12c225/History.rdoc#label-5.16.0+-2F+2022-06-14